version: '3.8'
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - db_data:/root/db
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db_data:/root/db
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  db_data: